---
title: "gchs.trevorfrench.com"
format:
  revealjs: 
    theme: [simple, custom.scss]
---

## Agenda

1.  Career (GCHS - Present)

2.  Crypto Journey

3.  Crypto Basics

4.  Software Demo

5.  Hardware Demo

6.  Opportunities

7.  Q&A

## Career - Education {.smaller .scrolable}

-   **GCHS (Class of 2014)**

    -   Best class

-   **FTCC (2015 - 2016)**

-   **Brigham Young University-Idaho (2016 - 2019)**

    -   B.S. Business Analytics

-   **Western Governors University (2019 - 2020)**

    -   M.S. Data Analytics

-   **University of the Cumberlands (2024 - 2028)**

    -   Ph.D. Information Technology, Specialization in Artificial Intelligence

## Career - Work History {.smaller .scrollable}

-   **Insight Pest Solutions**

    -   Data Analyst Intern, 03/2018 - 07/2018

-   **BYU-I**

    -   Data Analyst, 05/2018 - 03/2019

    -   Analytics Manager, 04/2019 - 07/2019

-   **Ecolab**

    -   Territory Manager, 08/2019 - 12/2020

-   **Swire Coca-Cola**

    -   Data Analyst, 12/2020 - 09/2021

-   **TaxBit**

    -   Data Analyst, 09/2021 - 03/2022

    -   Analytics Manager, 04/2022 - 10/2023

    -   Data Science Consultant, 10/2023 - Present

-   **USASOC AI Division**

    -   Data Scientist, 10/2023 - Present

## Career - Links {.smaller .scrollable}

-   Portfolio

-   LinkedIn

-   GitHub

-   Medium

-   R for Data Analysis

    -   Book

    -   Paper

## Crypto Journey  {.smaller .scrollable}

-   **2019**

    -   Personal Investing

-   **2020**

    -   Launched an [ERC-20 token](https://etherscan.io/address/0x1b052168aBEF0A2484f4f6BB9814cFADec3c49D5)

-   **2021**

    -   Joined TaxBit

    -   Registered [trevorfrench.eth](https://etherscan.io/name-lookup-search?id=trevorfrench.eth)

    -   [Contributed code](https://github.com/ethereum/ethereum-org-website/issues/3932) to Ethereum.org

    -   [Joined Developer DAO](https://etherscan.io/tx/0xcd9ab01458d56087b5d13396253e366a53c1bde5e1ae29de6e2ba49caa297c33)

    -   [ENS Airdrop](https://etherscan.io/tx/0x48b1de228f5e3dfdeb993728521df61e347904b41fcf6e6e9249d70ac7b941a9)

    -   Set up 3 [Helium Miners](https://explorer.helium.com/hex/882ad66453fffff)

-   **2022**

    -   Developed [1099-DA Model](https://www.taxnotes.com/featured-news/irs-prepping-least-8-billion-crypto-information-returns/2023/10/25/7hhdp) for IRS

    -   Developed crypto pricing API for PayPal

    -   Launched [cryptotrackr](https://github.com/TrevorFrench/cryptotrackr) v1.0.0

-   **2023**

    -   [John Doe Summons](https://www.justice.gov/opa/pr/court-authorizes-service-john-doe-summons-seeking-identities-us-taxpayers-who-have-used-0) Circle/Poloniex

    -   cryptotrackr [v.1.1.0](https://github.com/TrevorFrench/cryptotrackr/tree/v1.1)

-   **2024**

    -   [Jupiter Airdrop](https://solscan.io/tx/4oHcsGUKACJ5gwbJxPLUZW7mukGqz9mnEREbSCCAYuXSn4kCS24haYjUsgDkp7XUBzRVHjvEqvJMuWPGRTQJStgt)

    -   cryptotrackr [v.1.2.0](https://doi.org/10.5281/zenodo.10775699)
